# Site settings
title: "Martin van der Schelling"
description: "Resume of Martin van der Schelling"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Martin van der Schelling"
resume_title:                   "MSc Materials Science & Engineering"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "mpvanderschelling@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • mpvanderschelling@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>	<b>Hi!</b> I'm trying to implement <b>computational modelling</b> and optimization with materials science. With my chemical background, I'm curious about the world of <b>plastics and composites</b>. During my sustainability minor, I've gained an interest in <b>renewable energy</b> and technology. I'm ready to take on the challenges that come with the clean energy transition and to give value to waste-stream processes. Besides, I play the piano in a cover band!





<br><br>I'm looking for a challenging role within an innovative company to kickstart my career! </p>"


collapsed_text: "To enhance the performance of an organic solar cell, it is essential to investigate the microscopic features that affect the charge mobility in semiconducting materials. The co-polymer indacenodithiophene-benzothiadiazole (C<sub>16</sub>-IDTBT) has shown promising results for high mobility hole transfer. This research attempts to integrate the microscopic dynamics of this co-polymer onto the macroscopic simulation program ToFeT. The Time-of-Flight and field-effect transistor mobility measurements methods and their implementation in the simulation code are described. Subsequently, a network of inter and intramolecular interactions is built, and the morphology of C<sub>16</sub>-IDTBT is extracted from a molecular dynamics simulation in Gromacs. The resulting mobilities are compared with transient SCLC and FET experimental data from literature. The time-of-flight mobilities show similar behaviour with experimental transient SCLC mobilities. The electric field dependence can be explained by charges getting stuck at the end of chains with a higher field. The simulated mobility values are slightly higher than the experimental transient SCLC mobilities. This can be explained by the lack of implementing a transfer integral decay on the intermolecular separation distance. The field-effect-transistor simulation was unsuccessful and are not implemented in this report. In further research, more pair-wise interactions of a C<sub>16</sub>-IDTBT molecular dynamics simulation should be investigated. This additional data could be used to fit functions to vary the J-coupling. In conclusion, it is possible to simulate the charge mobility for long polymeric semiconductors using the Kinetic Monte Carlo ToFeT code."

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    true
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/mpvanderschelling"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/martin.vanderschelling"
  resume_linkedin_url:          "https://www.linkedin.com/in/mpvanderschelling/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
